### ISSUE TITLE
As a new user I want to get info about site functionality so that I can decide if I want to signup.

### ISSUE THREAD

**Issue by digitaljosh** [digitaljosh/meal-planner#23]
Standard 'ABOUT' page.

**Comment by JasonOnes** [comment]
Description of app on Splash page, yeah?

**Comment by digitaljosh** [comment]
Yeah. We can make a separate 'about' page or just put a description on splash page as you mentioned.

**Comment by digitaljosh** [comment]
Added an 'about' button that displays popup menu explaining app features.
