### ISSUE TITLE
Once logged in user can view calendar.

### ISSUE THREAD

**Issue by JasonOnes** [digitaljosh/meal-planner#4]
User is redirected upon login (post sign up) to her or his calendar.

**Comment by JasonOnes** [comment]
I haven't moved this to done as there is currently no calendar to view, this could be resolved by this evening however.

**Comment by digitaljosh** [comment]
@JasonOnes @oregon999 Once we find an appropriate calendar to use (fullcalendar.io?) and implement it we can close this issue.
